Repository SOPT-32ND-APP2-Myhouse/Myhouse_iOS, pull requests merged in 2023-05, with the labels that each got.

#4 [Setting] #3 - SwiftLint 적용
  Myhouse/.swiftlint.yml
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Presentation/ViewController.swift
Labels: Setting⚙️, 영린🍀

#8 [Feat] #7 - 오늘의 집 TabBar 구현
  Myhouse/Application/SceneDelegate.swift
  Myhouse/Global/Literals/SizeLiterals.swift
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Presentation/Common/BaseView.swift
  Myhouse/Presentation/Common/BaseViewController.swift
  Myhouse/Presentation/Common/TabBarViewController.swift
  Myhouse/Presentation/HomeScene/HomeViewController.swift
  Myhouse/Presentation/LifeScene/LifeViewController.swift
  Myhouse/Presentation/LookScene/DetailView/DetailViewController.swift
  Myhouse/Presentation/LookScene/LookView/LookViewController.swift
  Myhouse/Presentation/MyPageScene/MyPageViewController.swift
  Myhouse/Presentation/ShoppingScene/ShoppingViewController.swift
Labels: 영린🍀, UI

#12 [Feat] #9 - 오늘의 집 스크랩뷰 UI 구현
  Myhouse/Global/Literals/ImageLiterals.swift
  Myhouse/Global/Literals/SizeLiterals.swift
  Myhouse/Global/Resources/Assets.xcassets/img_card17.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/img_card17.imageset/Rectangle 251@1x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card17.imageset/Rectangle 251@2x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card17.imageset/Rectangle 251@3x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card18.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/img_card18.imageset/Rectangle 252@1x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card18.imageset/Rectangle 252@2x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card18.imageset/Rectangle 252@3x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card19.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/img_card19.imageset/Rectangle 253@1x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card19.imageset/Rectangle 253@2x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card19.imageset/Rectangle 253@3x.png
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Presentation/Common/BaseViewController.swift
  Myhouse/Presentation/HomeScene/Cell/BestCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/CategoryCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/ColorBestCollectionVIewCell.swift
  Myhouse/Presentation/HomeScene/Cell/ColorLightCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/ModernCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/RecommendCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/ReviewCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/TodaysIdeasCollectionVIewCell.swift
  Myhouse/Presentation/HomeScene/Cell/TodaysProductCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/Top10CollectionViewCell.swift
  Myhouse/Presentation/HomeScene/View/HomeView.swift
  Myhouse/Presentation/HomeScene/ViewModel/BestDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/ModernDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/RecommendDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/TodaysDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/categoryDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/colorLightDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/iconDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/modernDataModel.swift
  Myhouse/Presentation/HomeScene/ViewModel/todaysIdeasDataModel.swift
  Myhouse/Presentation/LookScene/ScarpView/Cell/ScrapCollectionViewCell.swift
  Myhouse/Presentation/LookScene/ScarpView/View/ScrapView.swift
  Myhouse/Presentation/LookScene/ScarpView/ViewController/ScarpViewController.swift
  Myhouse/Presentation/LookScene/ScarpView/ViewModel/ScrapDataModel.swift
Labels: 영린🍀, Feat, UI, 스크랩뷰

#15 [Feat] #14 - 폴더 선택 BottomSheet UI 구현
  Myhouse/Global/Literals/ImageLiterals.swift
  Myhouse/Global/Literals/StringLiterals.swift
  Myhouse/Global/Resources/Assets.xcassets/btn_delete.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/btn_delete.imageset/bt_X@1x.png
  Myhouse/Global/Resources/Assets.xcassets/btn_delete.imageset/bt_X@2x.png
  Myhouse/Global/Resources/Assets.xcassets/btn_delete.imageset/bt_X@3x.png
  Myhouse/Global/Resources/Assets.xcassets/btn_plus.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/btn_plus.imageset/Group 88@1x.png
  Myhouse/Global/Resources/Assets.xcassets/btn_plus.imageset/Group 88@2x.png
  Myhouse/Global/Resources/Assets.xcassets/btn_plus.imageset/Group 88@3x.png
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Presentation/Common/Scrap/FolderBottomSheetView.swift
  Myhouse/Presentation/Common/Scrap/FolderBottomSheetViewController.swift
  Myhouse/Presentation/Common/Scrap/FolderHeaderView.swift
  Myhouse/Presentation/Common/Scrap/FolderTableViewCell.swift
  Myhouse/Presentation/LookScene/ScarpView/ViewModel/ScrapDataModel.swift
Labels: 영린🍀, Feat, UI

#17 [Feat] #16 - 둘러보기 UI 구현
  Myhouse/Global/Literals/ImageLiterals.swift
  Myhouse/Global/Literals/SizeLiterals.swift
  Myhouse/Global/Literals/StringLiterals.swift
  Myhouse/Global/Resources/Assets.xcassets/icn_several.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/icn_several.imageset/Frame 71@1x.png
  Myhouse/Global/Resources/Assets.xcassets/icn_several.imageset/Frame 71@2x.png
  Myhouse/Global/Resources/Assets.xcassets/icn_several.imageset/Frame 71@3x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card01.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/img_card01.imageset/Rectangle 198@1x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card01.imageset/Rectangle 198@2x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card01.imageset/Rectangle 198@3x.png
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Presentation/Common/Scrap/ScrapButton.swift
  Myhouse/Presentation/LookScene/LookView/Cell/FeedCollectionViewCell.swift
  Myhouse/Presentation/LookScene/LookView/Cell/TagCollectionViewCell.swift
  Myhouse/Presentation/LookScene/LookView/LookViewController.swift
  Myhouse/Presentation/LookScene/LookView/View/LookCollectionView.swift
  Myhouse/Presentation/LookScene/LookView/ViewController/LookViewController.swift
  Myhouse/Presentation/LookScene/LookView/ViewModel/LookDataModel.swift
Labels: 영린🍀, Feat, UI, 둘러보기뷰

#25 [Feat] 스크랩 스낵바 UI 및 버튼 화면전환 구현
  Myhouse/Global/Literals/StringLiterals.swift
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Presentation/Common/Scrap/FolderBottomSheetView.swift
  Myhouse/Presentation/Common/Scrap/FolderBottomSheetViewController.swift
  Myhouse/Presentation/Common/Scrap/ScrapButton.swift
  Myhouse/Presentation/Common/Scrap/ScrapPopUpView.swift
  Myhouse/Presentation/Common/TabBarViewController.swift
  Myhouse/Presentation/LookScene/LookView/Cell/FeedCollectionViewCell.swift
  Myhouse/Presentation/LookScene/LookView/View/LookCollectionView.swift
  Myhouse/Presentation/LookScene/LookView/ViewController/LookViewController.swift
  Myhouse/Presentation/LookScene/LookView/ViewModel/LookDataModel.swift
Labels: 영린🍀, Feat, UI, 스크랩뷰

#27 [Feat] #26 - 홈화면, 둘러보기 UINavigationBar 구현
  Myhouse/Global/Literals/ImageLiterals.swift
  Myhouse/Global/Resources/Assets.xcassets/icn_cart_1.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/icn_cart_1.imageset/icn_cart_1@1x.png
  Myhouse/Global/Resources/Assets.xcassets/icn_cart_1.imageset/icn_cart_1@2x.png
  Myhouse/Global/Resources/Assets.xcassets/icn_cart_1.imageset/icn_cart_1@3x.png
  Myhouse/Presentation/Common/TabBarViewController.swift
  Myhouse/Presentation/LookScene/LookView/ViewController/LookViewController.swift
Labels: 영린🍀, Feat, UI, 둘러보기뷰

#29 [Feat] #28 - 둘러보기 뷰 카테고리 UI 구현
  Myhouse/Global/Literals/StringLiterals.swift
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Presentation/Common/Scrap/ScrapButton.swift
  Myhouse/Presentation/Common/TabBarViewController.swift
  Myhouse/Presentation/LookScene/LookView/Cell/LookPagingCollectionViewCell.swift
  Myhouse/Presentation/LookScene/LookView/Cell/LookPagingTabBarCollectionViewCell.swift
  Myhouse/Presentation/LookScene/LookView/View/LookCollectionView.swift
  Myhouse/Presentation/LookScene/LookView/View/LookPagingTabBarView.swift
  Myhouse/Presentation/LookScene/LookView/View/LookView.swift
  Myhouse/Presentation/LookScene/LookView/View/LookingPagingView.swift
  Myhouse/Presentation/LookScene/LookView/ViewController/LookViewController.swift
Labels: 영린🍀, Feat, UI, 둘러보기뷰

#33 [Setting] #32 - 네트워크 세팅
  Myhouse/Global/Resources/Info.plist
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Network/Base/BaseService.swift
  Myhouse/Network/Base/Config.swift
  Myhouse/Network/Base/GenericResponse.swift
  Myhouse/Network/Base/NetworkConstant.swift
  Myhouse/Network/Base/NetworkResult.swift
  Myhouse/Network/DataModel/Home/ProductResponseModel.swift
  Myhouse/Network/DataModel/Post/AllPostResponseModel.swift
  Myhouse/Network/DataModel/Scrap/AllScrapResponseModel.swift
  Myhouse/Network/DummyClass.swift
  Myhouse/Network/Service/HomeService.swift
  Myhouse/Network/Service/PostService.swift
  Myhouse/Network/Service/ScrapService.swift
Labels: Setting⚙️, 영린🍀

#40 [Feat] #36 - 모든 스크랩 보기 API 연결
  Myhouse/Global/Literals/ImageLiterals.swift
  Myhouse/Global/Resources/Assets.xcassets/img_card_default.imageset/Contents.json
  Myhouse/Global/Resources/Assets.xcassets/img_card_default.imageset/Rectangle 254@1x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card_default.imageset/Rectangle 254@2x.png
  Myhouse/Global/Resources/Assets.xcassets/img_card_default.imageset/Rectangle 254@3x.png
  Myhouse/Network/Base/Config.swift
  Myhouse/Network/DataModel/Scrap/AllScrapResponseModel.swift
  Myhouse/Network/Service/ScrapService.swift
  Myhouse/Presentation/Common/Scrap/FolderBottomSheetView.swift
  Myhouse/Presentation/Common/Scrap/FolderTableViewCell.swift
  Myhouse/Presentation/LookScene/ScarpView/Cell/ScrapCollectionViewCell.swift
  Myhouse/Presentation/LookScene/ScarpView/View/ScrapView.swift
Labels: 영린🍀, Feat, 스크랩뷰, API연결

#44 [Chore] #43 - swiftlint 규칙 수정
  Myhouse/.swiftlint.yml
Labels: Fix🛠

#48 [Feat] #46 - 둘러보기 상세보기 화면 연결
  Myhouse/Network/DataModel/Scrap/AllScrapResponseModel.swift
  Myhouse/Presentation/Common/Scrap/FolderTableViewCell.swift
  Myhouse/Presentation/Common/TabBarViewController.swift
  Myhouse/Presentation/LookScene/DetailView/ViewController/DetailViewController.swift
  Myhouse/Presentation/LookScene/LookView/View/LookCollectionView.swift
  Myhouse/Presentation/LookScene/LookView/ViewController/LookViewController.swift
  Myhouse/Presentation/LookScene/ScarpView/Cell/ScrapCollectionViewCell.swift
  Myhouse/Presentation/LookScene/ScarpView/ViewController/ScarpViewController.swift
Labels: Feat, UI

#50 [Feat] #39 - 홈뷰 API 연결
  Myhouse/Myhouse.xcodeproj/project.pbxproj
  Myhouse/Myhouse.xcodeproj/project.xcworkspace/xcuserdata/j.xcuserdatad/UserInterfaceState.xcuserstate
  Myhouse/Network/Base/Config.swift
  Myhouse/Network/DataModel/Home/PopularResponseModel.swift
  Myhouse/Network/DataModel/Home/ProductResponseModel.swift
  Myhouse/Network/DataModel/Home/RecomendResponseModel.swift
  Myhouse/Network/Service/HomeService.swift
  Myhouse/Presentation/HomeScene/Cell/BestCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/ContentCell.swift
  Myhouse/Presentation/HomeScene/Cell/PagingCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/Cell/RecommendCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/View/HomeView.swift
  Myhouse/Presentation/HomeScene/View/SectionTitleCollectionReusableView.swift
Labels: Feat, 민주🐤, 홈뷰, API연결

#56 [Fix] #55 - 홈뷰 오늘의딜 레이아웃 수정
  Myhouse/Presentation/HomeScene/Cell/TodaysDealCollectionViewCell.swift
  Myhouse/Presentation/HomeScene/View/HomeFooterView.swift
  Myhouse/Presentation/HomeScene/View/HomeView.swift
Labels: 민주🐤, UI, 홈뷰, Fix🛠
